id=ai-retrieval-augmented-generation
name=AI Retrieval Augmented Generation
version=${project.version}
description=${project.description}
class=io.gravitee.policy.ai.rag.AiRagPolicy
type=policy
category=ai
proxy=REQUEST
message=REQUEST
